# Generated by Django 5.1 on 2024-12-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp1', '0004_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
